import { createStore } from 'vuex'

export default createStore({
  state: {
    building: [
      {
        id: 1,
        name: "ЖК River House",
        street: 'ул. Осипенко',
        metro: 'Алабинская',
        time: '5 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: false,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: false,
        image: 'image-1.jpg'
      },
      {
        id: 2,
        name: "ЖК Атмосфера",
        street: 'ул. Ново-Садовая',
        metro: 'Российская',
        time: '15 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: false,
        image: 'image-2.jpg'
      },
      {
        id: 3,
        name: "ЖК Артхолл",
        street: 'ул. Гая',
        metro: 'Московская',
        time: '15 минут пешком',
        term: 'В следующем году',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: false,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-3.jpg'
      },
      {
        id: 4,
        name: "ЖК Эталон",
        street: 'ул. Революционная',
        metro: 'Гагаринская',
        time: '10 минут пешком',
        term: 'В этом году',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: false,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-4.jpg'
      },
      {
        id: 5,
        name: "ЖК Капитал",
        street: 'ул. Дыбенко',
        metro: 'Спортивная',
        time: '15 минут пешком',
        term: 'В следующем году',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: false,
        repair: true,
        lowRise: true,
        penthouse: true,
        image: 'image-5.jpg'
      },
      {
        id: 6,
        name: "ЖК Рассвет",
        street: 'ул. Гагарина',
        metro: 'Советская',
        time: '10 минут пешком',
        term: 'В следующем году',
        credit: true,
        comfort: true,
        parking: false,
        school: false,
        kindergarten: true,
        studio: false,
        repair: false,
        lowRise: false,
        penthouse: false,
        image: 'image-6.jpg'
      },
      {
        id: 7,
        name: "ЖК Феникс",
        street: 'ул. Свободы',
        metro: 'Победы',
        time: '5 минут пешком',
        term: 'В этом году',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-7.jpg'
      },
      {
        id: 8,
        name: "ЖК Акварель",
        street: 'ул. Ново-Вокзальная',
        metro: 'Безымянка',
        time: '10 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: false,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: false,
        image: 'image-8.jpg'
      },
      {
        id: 9,
        name: "ЖК Адмирал",
        street: 'ул. Краснодонская',
        metro: 'Кировская',
        time: '10 минут пешком',
        term: 'В следующем году',
        credit: true,
        comfort: false,
        parking: true,
        school: true,
        kindergarten: false,
        studio: false,
        repair: false,
        lowRise: false,
        penthouse: true,
        image: 'image-9.jpg'
      },
      {
        id: 10,
        name: "ЖК Рекорд",
        street: 'пр. Ленина',
        metro: 'Алабинская',
        time: '20 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-10.jpg'
      },
      {
        id: 11,
        name: "ЖК Боярский двор",
        street: 'ул. Николая Панова',
        metro: 'Российская',
        time: '15 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-11.jpg'
      },
      {
        id: 12,
        name: "ЖК Зодиак",
        street: 'ул. Киевская',
        metro: 'Московская',
        time: '10 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: false,
        parking: true,
        school: false,
        kindergarten: true,
        studio: true,
        repair: false,
        lowRise: false,
        penthouse: true,
        image: 'image-12.jpg'
      },
      {
        id: 13,
        name: "ЖК Академик",
        street: 'ул. Авроры',
        metro: 'Спортивная',
        time: '10 минут пешком',
        term: 'Сдан',
        credit: false,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: true,
        penthouse: true,
        image: 'image-13.jpg'
      },
      {
        id: 14,
        name: "ЖК Элеон",
        street: 'ул. Победы',
        metro: 'Победы',
        time: '5 минут пешком',
        term: 'В этом году',
        credit: true,
        comfort: false,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: false,
        image: 'image-14.jpg'
      },
      {
        id: 15,
        name: "ЖК Эндшпиль",
        street: 'ул. Мичурина',
        metro: 'Российская',
        time: '15 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-15.jpg'
      },
      {
        id: 16,
        name: "ЖК Зеон",
        street: 'ул. Георгия Димитрова',
        metro: 'Кировская',
        time: '30 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-16.jpg'
      },
      {
        id: 17,
        name: "ЖК Рихард",
        street: 'ул. Солнечная',
        metro: 'Кировская',
        time: '40 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: false,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: false,
        image: 'image-17.jpg'
      },
      {
        id: 18,
        name: "ЖК Созвездие",
        street: 'ул. 6-просека',
        metro: 'Безымянка',
        time: '40 минут пешком',
        term: 'В этом году',
        credit: true,
        comfort: false,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: false,
        lowRise: false,
        penthouse: false,
        image: 'image-18.jpg'
      },
      {
        id: 19,
        name: "ЖК Гагаринский",
        street: 'ул. Стара-Загора',
        metro: 'Советская',
        time: '20 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: false,
        image: 'image-19.jpg'
      },
      {
        id: 20,
        name: "ЖК Космос",
        street: 'ул. Академика Павлова',
        metro: 'Российская',
        time: '20 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-20.jpg'
      },
      {
        id: 21,
        name: "ЖК Прогресс",
        street: 'Заводское шоссе',
        metro: 'Юнгородок',
        time: '15 минут пешком',
        term: 'В следующем году',
        credit: true,
        comfort: false,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: false,
        lowRise: false,
        penthouse: false,
        image: 'image-21.jpg'
      },
      {
        id: 22,
        name: "ЖК Южный полюс",
        street: 'ул. Лазурная',
        metro: 'Спортивная',
        time: '35 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: false,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: false,
        lowRise: false,
        penthouse: false,
        image: 'image-22.jpg'
      },
      {
        id: 23,
        name: "ЖК Фэймос",
        street: 'ул. Ново-Садовая',
        metro: 'Безымянка',
        time: '35 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-23.jpg'
      },
      {
        id: 24,
        name: "ЖК Will Towers",
        street: 'ул. Лейтенанта Шмидта',
        metro: 'Безымянка',
        time: '45 минут пешком',
        term: 'Сдан',
        credit: false,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-24.jpg'
      },
      {
        id: 25,
        name: "ЖК Лунный свет",
        street: 'ул. Луначарского',
        metro: 'Российская',
        time: '5 минут пешком',
        term: 'В этом году',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-25.jpg'
      },
      {
        id: 26,
        name: "ЖК Волжский пасад",
        street: 'ул. Травяная',
        metro: 'Российская',
        time: '25 минут пешком',
        term: 'В следющем году',
        credit: false,
        comfort: true,
        parking: true,
        school: false,
        kindergarten: false,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-26.jpg'
      },
      {
        id: 27,
        name: "ЖК Интонация",
        street: 'ул. Южная',
        metro: 'Спортивная',
        time: '45 минут пешком',
        term: 'В этом году',
        credit: true,
        comfort: false,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: false,
        lowRise: false,
        penthouse: false,
        image: 'image-27.jpg'
      },
      {
        id: 28,
        name: "ЖК Симфония",
        street: 'ул. Цветочная',
        metro: 'Спортивная',
        time: '45 минут пешком',
        term: 'В следующем году',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: false,
        lowRise: false,
        penthouse: false,
        image: 'image-28.jpg'
      },
      {
        id: 29,
        name: "ЖК Slava",
        street: 'ул. Самарская',
        metro: 'Алабинская',
        time: '20 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-29.jpg'
      },
      {
        id: 30,
        name: "ЖК Sydney City",
        street: 'ул. Лесная',
        metro: 'Алабинская',
        time: '20 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: false,
        image: 'image-30.jpg'
      },
      {
        id: 31,
        name: "ЖК Victory Park Residences",
        street: 'ул. 1-я Просека',
        metro: 'Российская',
        time: '25 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: true,
        school: false,
        kindergarten: true,
        studio: false,
        repair: true,
        lowRise: true,
        penthouse: true,
        image: 'image-31.jpg'
      },
      {
        id: 32,
        name: "ЖК Врубеля",
        street: 'ул. Врубеля',
        metro: 'Российская',
        time: '15 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: false,
        image: 'image-32.jpg'
      },
      {
        id: 33,
        name: "ЖК Роттердам",
        street: 'ул. Бубнова',
        metro: 'Кировская',
        time: '35 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-33.jpg'
      },
      {
        id: 34,
        name: "ЖК Квартал",
        street: 'ул. Боярова',
        metro: 'Юнгородок',
        time: '5 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: false,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: false,
        lowRise: false,
        penthouse: false,
        image: 'image-34.jpg'
      },
      {
        id: 35,
        name: "ЖК Noble",
        street: 'ул. Ленинградская',
        metro: 'Алабинская',
        time: '20 минут пешком',
        term: 'В следующем году',
        credit: false,
        comfort: true,
        parking: false,
        school: false,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-35.jpg'
      },
      {
        id: 36,
        name: "ЖК Просеки",
        street: 'ул. 9-просека',
        metro: 'Кировская',
        time: '45 минут пешком',
        term: 'Сдан',
        credit: false,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: false,
        repair: true,
        lowRise: true,
        penthouse: true,
        image: 'image-36.jpg'
      },
      {
        id: 37,
        name: "ЖК Просеки",
        street: 'ул. Молодежная',
        metro: 'Спортивная',
        time: '60 минут пешком',
        term: 'В следующем году',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-37.jpg'
      },
      {
        id: 38,
        name: "ЖК Звезда",
        street: 'ул. Советской Армии',
        metro: 'Советская',
        time: '25 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: false,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-38.jpg'
      },
      {
        id: 39,
        name: "ЖК Звезда",
        street: 'ул. Мяги',
        metro: 'Гагаринская',
        time: '15 минут пешком',
        term: 'В этом году',
        credit: true,
        comfort: false,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: false,
        image: 'image-39.jpg'
      },
      {
        id: 40,
        name: "ЖК Будущее",
        street: 'ул. Тухачевского',
        metro: 'Московская',
        time: '15 минут пешком',
        term: 'В следующем году',
        credit: true,
        comfort: true,
        parking: true,
        school: false,
        kindergarten: false,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: false,
        image: 'image-40.jpg'
      },
      {
        id: 41,
        name: "ЖК На Волге",
        street: 'ул. Максима Горького',
        metro: 'Алабинская',
        time: '35 минут пешком',
        term: 'Сдан',
        credit: false,
        comfort: true,
        parking: true,
        school: false,
        kindergarten: true,
        studio: false,
        repair: true,
        lowRise: true,
        penthouse: true,
        image: 'image-41.jpg'
      },
      {
        id: 42,
        name: "ЖК Цветочная поляна",
        street: 'ул. Белорусская',
        metro: 'Алабинская',
        time: '60 минут пешком',
        term: 'В следующем году',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: false,
        image: 'image-42.jpg'
      },
      {
        id: 43,
        name: "ЖК Домино",
        street: 'ул. Владимирская',
        metro: 'Гагаринская',
        time: '20 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: false,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: false,
        lowRise: false,
        penthouse: false,
        image: 'image-43.jpg'
      },
      {
        id: 44,
        name: "ЖК Куйбышев",
        street: 'ул. Галактионовская',
        metro: 'Алабинская',
        time: '30 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: true,
        school: false,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-44.jpg'
      },
      {
        id: 45,
        name: "ЖК Огни Самары",
        street: 'ул. Лесная',
        metro: 'Российская',
        time: '15 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-45.jpg'
      },
      {
        id: 46,
        name: "ЖК Династия",
        street: 'ул. Антонова-Овсеенко',
        metro: 'Советская',
        time: '15 минут пешком',
        term: 'В этом году',
        credit: true,
        comfort: false,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: false,
        lowRise: false,
        penthouse: false,
        image: 'image-46.jpg'
      },
      {
        id: 47,
        name: "ЖК Sky Garden",
        street: 'Московское шоссе',
        metro: 'Московская',
        time: '5 минут пешком',
        term: 'В этом году',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-47.jpg'
      },
      {
        id: 48,
        name: "ЖК Nice Loft",
        street: 'ул. Часовая',
        metro: 'Российская',
        time: '15 минут пешком',
        term: 'В этом году',
        credit: true,
        comfort: true,
        parking: false,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-48.jpg'
      },
      {
        id: 49,
        name: "ЖК Летний сад",
        street: 'ул. 3-я просека',
        metro: 'Советская',
        time: '55 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: true,
        school: true,
        kindergarten: true,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-49.jpg'
      },
      {
        id: 50,
        name: "ЖК Синий кит",
        street: 'ул. Полевая',
        metro: 'Алабинская',
        time: '15 минут пешком',
        term: 'Сдан',
        credit: true,
        comfort: true,
        parking: false,
        school: true,
        kindergarten: false,
        studio: true,
        repair: true,
        lowRise: false,
        penthouse: true,
        image: 'image-50.jpg'
      },
    ]
  },
  getters: {
    getBuildings(state) {
      return state.building
    }
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  }
})
